### PR TITLE
Added Create and Delete ACL Feature To Admin Functions (#244)

### PR DESCRIPTION
**Pull request by mensfeld**

### CODE REVIEW

**Comment by mensfeld** [comment]
@vgnanasekaran ready and green :)

**Review by nijikon — APPROVED** [review]

**Comment by vgnanasekaran** [comment]
Thank you @mensfeld for following up and verifying the changes. @nijikon thank you for approving the changes.

**Comment by vgnanasekaran** [comment]
@mensfeld thank you for support. Glad to see that the changes are now in the main stream.

**Comment by mensfeld** [comment]
@vgnanasekaran thank you for this work, and sorry once again it took so much time. The handover of this gem and my cleanups, and backporting takes time but this should go live in 1-2 weeks tops.

After that I should be able to provide a steady stream of updates and improvements to this library.

**Comment by vgnanasekaran** [comment]
@mensfeld you don't have to say sorry. I know how difficult it is to manage an open-source library in addition to your work.

**Pull request merged**
