### PR TITLE
fix Style/StringLiterals in specs

### PR DESCRIPTION
**Pull request by nijikon**

### CODE REVIEW

**Comment by mensfeld** [comment]
@nijikon just for the record: withholding this just so we can run standardrb or something similar on it.

**Comment by nijikon** [comment]
Whatever you think it's best. My personal preference is 'rubocop' with defaults.

**Comment by mensfeld** [comment]
@nijikon sorry no update. I still need to setup standardrb or something similar.

**Comment by nijikon** [comment]
Ouf-of-sync

**Pull request closed without merging**
