### PR TITLE
Fix segfault on exit

### PR DESCRIPTION
**Pull request by thijsc**
Work in progress, trying to root out any remaining segfaults.

### CODE REVIEW

**Comment by mensfeld** [comment]
Can we expose the native kafka on admin? Otherwise I need to do tricks like so:

```ruby
Rdkafka::Metadata.new(admin.instance_variable_get('@native_kafka').inner)
```

**Comment by thijsc** [comment]
It's not really something that a normal user would need. Do you need it just for the stability test? Or also from normal code?

**Comment by mensfeld** [comment]
I'm not a normal user ;) I need it for both stability as well as my internal work on the UI for karafka. I can patch it but then it creates issues like the one above :sweat:

**Comment by mensfeld** [comment]
1. Messages production works as expected. Since I support various versions of rdkafka in WaterDrop I run it locally against few and new one behaves the same way.

**Comment by mensfeld** [comment]
2. Messages consumption + admin works as expected. I do not run specs atm against various versions of rdkafka (would eat up a lot of CI but I probably should) but I run my stress suite against 0.13 and no failures and no behavior deviations.

**Pull request merged**
